# GitHub Action for generating a AppleWatchHeartBeat

name: Generate HeartBeat

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'time list'
        required: false
      value:
        description: 'value list'
        required: false

env:
  GITHUB_NAME: ${{ secrets.PROFILE_COMMIT_NAME }}
  GITHUB_EMAIL: ${{ secrets.PROFILE_COMMIT_EMAIL }}

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go version

      - name: Get generate SVG
        run: |
          go run main.go '${{ github.event.inputs.time }}' '${{ github.event.inputs.value }}'
      - name: Push README
        run: |
          git add assets/heart.svg
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'chore: update heart svg' || echo "nothing to commit"
          git push || echo "nothing to push"
